#!/usr/bin/env bun
// Uninstall every extension and preset shipped in this repo from a Spec Kit
// project. Only de-registers from <project-dir>/.specify/; this repo is untouched.
// Items not installed are skipped (specify's own output, trimmed to 3 lines).
//
// Usage: ./uninstall.ts <project-dir>
import { existsSync, readFileSync, readdirSync, rmSync, statSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { KINDS, cmp, manifests } from "./scripts/manifest.ts";

const REPO_DIR = import.meta.dir;
const projectArg = process.argv[2];
if (!projectArg) {
  console.error(`usage: ${basename(process.argv[1] ?? "uninstall.ts")} <project-dir>`);
  process.exit(2);
}

const isDir = (p: string): boolean => {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
};
if (!isDir(join(projectArg, ".specify"))) {
  console.error(`error: ${projectArg} is not a Spec Kit project (.specify/ missing)`);
  process.exit(1);
}
const PROJECT_DIR = resolve(projectArg);
process.chdir(PROJECT_DIR);

const run = (cmd: string[]): void => {
  Bun.spawnSync(cmd, { stdio: ["inherit", "inherit", "inherit"] });
};

// Harness wiring added by post-install (.claude/settings.json, CLAUDE.md) is outside
// specify's reach, so it comes out before de-registration: scripts/ts/pre-uninstall.ts.
for (const [kind] of KINDS) {
  const dir = join(REPO_DIR, kind);
  const ids = existsSync(dir) ? readdirSync(dir).filter((n) => !n.startsWith(".") && isDir(join(dir, n))).sort(cmp) : [];
  for (const id of ids) {
    const pre = join(dir, id, "scripts/ts/pre-uninstall.ts");
    if (!existsSync(pre)) continue;
    console.log(`==> pre-uninstall: ${id}`);
    run([process.execPath, pre, PROJECT_DIR]); // failures ignored, as before
  }
}

for (const [kind, manifest] of KINDS) {
  const noun = kind === "extensions" ? "extension" : "preset";
  for (const { id } of manifests(REPO_DIR, kind, manifest)) {
    console.log(`==> ${noun}: ${id}`);
    run(["sh", "-c", 'yes | specify "$1" remove "$2" 2>&1 | tail -3', "sh", noun, id]);
  }
}

// The generated agent script index describes only this repo's items; remove it too.
for (const f of [".specify/extensions/AGENTS.md", ".specify/scripts/bash/README.md"]) {
  try {
    if (!readFileSync(f, "utf8").split("\n", 1)[0]?.includes("generated by speckit-squads-ios")) continue;
  } catch {
    continue;
  }
  rmSync(f, { force: true });
  console.log(`==> removed ${f}`);
}

console.log(`\nDone. Uninstalled from: ${PROJECT_DIR}`);
