#!/usr/bin/env bun
/**
 * Generate the agent-facing script index INTO a consumer project.
 *
 * The installed layout does not match this repo's layout, and command names do not
 * predict script names (`/speckit-git-feature` runs `create-new-feature.ts`). An agent
 * working in a consumer project cannot see this repo's CLAUDE.md, so the mapping has to
 * travel with the install. Writes two files, both regenerated on every `install.ts --force`:
 *
 *   <project>/.specify/extensions/AGENTS.md    command -> script table + layout rules
 *   <project>/.specify/scripts/bash/README.md  breadcrumb in the flat core tree
 *
 * Usage: gen-agent-index.ts <repo-dir> <project-dir>
 * bun/node built-ins only.
 */
import { readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { KINDS, cmp, manifests, scriptsBlock } from "./manifest.ts";

const GENERATED = "<!-- generated by speckit-squads gen-agent-index.ts — do not edit -->";

type Row = { cmd: string | null; installed: string };

/** (file, command|null) per `- name:` entry, in declaration order. */
function entries(block: string): [string, string | null][] {
  const out: [string, string | null][] = [];
  let cur: Record<string, string> = {};
  const flush = (): void => {
    const file = cur["file"];
    if (file) out.push([file, cur["command"] ?? null]);
  };
  for (const line of block.split("\n")) {
    const s = line.trim();
    if (s.startsWith("- name:")) {
      flush();
      cur = {};
    }
    for (const key of ["file", "command"]) {
      const m = new RegExp(`^-?\\s*${key}:\\s*["']?([^"'\\s]+)`).exec(s);
      if (m?.[1]) cur[key] = m[1];
    }
  }
  flush();
  return out;
}

function collect(repo: string): { owned: Row[]; shared: Row[] } {
  const owned: Row[] = [];
  const shared: Row[] = [];
  for (const [kind, manifest] of KINDS) {
    for (const { path, id } of manifests(repo, kind, manifest)) {
      const block = scriptsBlock(readFileSync(path, "utf8"));
      for (const [rel, cmd] of entries(block)) {
        const installed = `.specify/${kind}/${id}/${rel}`;
        (cmd ? owned : shared).push({ cmd, installed });
      }
    }
  }
  owned.sort((a, b) => cmp(a.cmd ?? "", b.cmd ?? "") || cmp(a.installed, b.installed));
  shared.sort((a, b) => cmp(a.installed, b.installed));
  return { owned, shared };
}

function isDir(p: string): boolean {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

function main(): void {
  const args = process.argv.slice(2);
  if (args.length !== 2) {
    process.stderr.write("usage: gen-agent-index.ts <repo-dir> <project-dir>\n");
    process.exit(1);
  }
  const [repo, project] = args as [string, string];
  const { owned, shared } = collect(repo);

  const rows = owned.map((r) => `| \`/${(r.cmd ?? "").replaceAll(".", "-")}\` | \`${r.installed}\` |`).join("\n");
  const lib = shared.map((r) => `- \`${r.installed}\``).join("\n");

  const index = `${GENERATED}
# Extension & preset scripts — where they actually live

**Do not guess a script path.** Command names do not predict script names:
\`/speckit-git-feature\` runs \`create-new-feature.ts\`, not \`feature.ts\`.

## Layout

There are two script trees, and they never merge:

\`\`\`
.specify/scripts/bash/                  core Spec Kit only — FLAT, no subdirectories
.specify/extensions/<id>/scripts/...    one tree per extension
.specify/presets/<id>/scripts/...       one tree per preset
\`\`\`

\`.specify/scripts/bash/<extension-id>/\` does not exist and never will — \`specify\`
copies each extension whole into \`.specify/extensions/<id>/\` and never merges its
scripts into the core tree. Note also that \`create-new-feature\` exists in *both*
trees as two different scripts: core \`.sh\` and the git extension's \`.ts\`.

## Command → script

| command | script |
| --- | --- |
${rows}

## Libraries and shared scripts

Sourced or shared by the above; no single command owns them.

${lib}

Regenerate with \`./install.ts --force <project>\` from the speckit-squads repo.
`;

  const breadcrumb = `${GENERATED}
# This is the core Spec Kit script tree — it is FLAT

Extension and preset scripts are **not** here and never will be. There is no
\`<extension-id>/\` subdirectory in this tree.

Look in \`.specify/extensions/<id>/scripts/ts/\` or \`.specify/presets/<id>/scripts/ts/\`.
The full command → script table is at \`.specify/extensions/AGENTS.md\`.
`;

  const wrote: string[] = [];
  for (const [rel, body] of [
    [".specify/extensions/AGENTS.md", index],
    [".specify/scripts/bash/README.md", breadcrumb],
  ] as const) {
    const dest = join(project, rel);
    if (!isDir(dirname(dest))) continue;
    writeFileSync(dest, body);
    wrote.push(rel);
  }
  console.log(`agent script index: wrote ${wrote.join(", ")} (${owned.length} commands mapped)`);
}

main();
